name: particles
version: 0.0.1
author: Volk <templar.volk@yandex.com>
description: A Dart library for creating particles"
homepage: https://github.com/TemplarVolk/particles
environment:
  sdk: '>=2.0.0 <3.0.0'